import os

import sourcer


project_home = os.path.dirname(__file__)


def read_grammar():
    with open(os.path.join(project_home, 'grammar.txt')) as f:
        return f.read()


def run(description):
    grammar = sourcer.Grammar(description, include_source=True)

    with open('spk/parser.py', 'w') as f:
        f.write(f'# Generated by ../{os.path.basename(__file__)}\n')
        f.write(grammar._source_code)


if __name__ == '__main__':
    run(read_grammar())
